LimaArrendamentos/Controllers/RealtyController.cs
using LimaArrendamentos.Data;
using LimaArrendamentos.Data.Entities;
using LimaArrendamentos.Helpers;
using LimaArrendamentos.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace LimaArrendamentos.Controllers
{
    public class RealtyController : Controller
    {
        private readonly DataContext _context;
        private readonly IRealtyRepository _realtyRepository;
        private readonly IUserHelper _userHelper;
        private readonly IBlobHelper _blobHelper;
        private readonly IAdvertHelper _advertHelper;
        private readonly IConverterHelper _converterHelper;
        private readonly ITypologyRepository _typologyRepository;
        private readonly IEnergyClassRepository _energyClassRepository;
        private readonly ISendEmailRepository _sendGmailRepository;
        private readonly IFavoriteRepository _favoriteRepository;
        private readonly IPropertyTypeRepository _propertyTypeRepository;

        public RealtyController(
            DataContext context,
            IRealtyRepository realtyRepository,
            IUserHelper userHelper,
            IConverterHelper converterHelper,
            ITypologyRepository typologyRepository,
            IEnergyClassRepository energyClassRepository,
            ISendEmailRepository sendGmailRepository,
            IFavoriteRepository favoriteRepository,
            IPropertyTypeRepository propertyTypeRepository,
            IBlobHelper blobHelper,
            IAdvertHelper advertHelper)
        {
            _context = context;
            _realtyRepository = realtyRepository;
            _userHelper = userHelper;
            _converterHelper = converterHelper;
            _typologyRepository = typologyRepository;
            _energyClassRepository = energyClassRepository;
            _sendGmailRepository = sendGmailRepository;
            _favoriteRepository = favoriteRepository;
            _propertyTypeRepository = propertyTypeRepository;
            _blobHelper = blobHelper;
            _advertHelper = advertHelper;
        }
        
        bool IsUsernameDetails = false;
        
        // GET: Products
        [Authorize(Roles = "Admin, Cliente")]
        public IActionResult Index(/*bool? IsUsername*/)
        {

            if (User.IsInRole("Admin"))
            {
                if (TempData["UserNameLease"] != null)
                {
                    ViewBag.UserName = TempData["UserNameLease"];

                    TempData["UserNameLease"] = null;
                }

                return View(_realtyRepository.GetAll().OrderBy(p => p.CreatedInSite));

            }
            else 
            {

                TempData["UserNameLease"] = null;

                return View(_realtyRepository.GetAll().Where(p => p.User.Email == User.Identity.Name).OrderBy(p => p.CreatedInSite));

            }


            //if (IsUsername == true)
            //{
            //    if (TempData["UserNameLessee"] != null)
            //    {
            //        ViewBag.UserName = TempData["UserNameLessee"];

            //        TempData["UserNameLessee"] = null;
            //    }
            //}
            //else
            //{
            //    TempData["UserNameLessee"] = null;
            //}
            ////if (User.IsInRole("Admin"))
            ////{
            //return View(_realtyRepository.GetAll().OrderBy(p => p.CreatedInSite));
            ////}
            ////else
            ////{
            ////    return View(_realtyRepository.GetAll().Where(p => p.User.Email == User.Identity.Name).OrderBy(p => p.CreatedInSite));
            ////}
        }

        public async Task<IActionResult> Index1(string Typology)
        {          
            if (Typology != null)
            {
                var a = _realtyRepository.GetAllWithPrecomin(Typology);
                return View(a);
            }

            
            var aa = _realtyRepository.GetAll();

            await _advertHelper.GetAdApi();

            return View(_realtyRepository.GetAll().OrderBy(p => p.CreatedInSite));           
        }

        // GET: Products/Details/5
        //[Authorize(Roles = "Admin, Cliente")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("RealtyNotFound");
            }

            var realty = await _realtyRepository.GetByIdAsync(id.Value);
            if (realty == null)
            {
                return new NotFoundViewResult("RealtyNotFound");
            }

            foreach (var item in _realtyRepository.GetAll().Where(p => p.User.Email == User.Identity.Name))
            {
                if (id == item.Id)
                {
                    var model = _converterHelper.ToRealtiesViewModel(realty);
                    return View(model);
                }
            }

            return View(realty);
        }


        //// GET: Products/Create
        [Authorize(Roles = "Cliente")]
        public IActionResult Create()
        {

            var model = new RealtyViewModel
            {
                Typologies = _typologyRepository.GetComboTypologies(),
                EnergiesClass = _energyClassRepository.GetComboEnergyClass(),
                PropertyTypes = _propertyTypeRepository.GetComboPropertyType(),
            };

            return View(model);
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]

        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Cliente")]
        public async Task<IActionResult> Create(RealtyViewModel modelView)
        {

            if (ModelState.IsValid)
            {

                Guid imageId = Guid.Empty;

                if (modelView.ImageFile != null && modelView.ImageFile.Length > 0)
                {

                    imageId = await _blobHelper.UploadBlobAsync(modelView.ImageFile, "realties");
                }

                //tipologia
                var typology = await _typologyRepository.GetTypologiesAsync(modelView.TypologyId);

                modelView.Typology = typology.TypologyDesc;
                modelView.TypologyId = typology.Id;

                var a = modelView.price;


                //classe energetica
                var energyClass = await _energyClassRepository.GetEnergyClassAsync(modelView.EnergyClassId);

                modelView.EnergyClass = energyClass.EnergyClassDesc;
                modelView.EnergyClassId = energyClass.Id;


                //tipo de propriedade
                var propertyType = await _propertyTypeRepository.GetPropertyTypeAsync(modelView.PropertyTypeId);

                modelView.PropertyType = propertyType.PropertyTypeDesc;
                modelView.PropertyTypeId = propertyType.Id;


                var realty = _converterHelper.ToRealty(modelView, imageId, true, User.Identity.Name);

                realty.User = await _userHelper.GetUserByEmailAsync(this.User.Identity.Name);
                await _realtyRepository.CreateAsync(realty);


                return RedirectToAction(nameof(Index));
            }
            return View(modelView);
        }



        //// GET: Products/Edit/5

        public async Task<IActionResult> Edit(int? id)
        {


            if (id == null)
            {
                return new NotFoundViewResult("RealtyNotFound");
            }

            var realty = await _realtyRepository.GetByIdAsync(id.Value);



            if (realty == null)
            {
                return new NotFoundViewResult("RealtyNotFound");
            }
            foreach (var item in _realtyRepository.GetAll().Where(p => p.User.UserName == User.Identity.Name))
            {
                if (id == item.Id)
                {
                    var model = _converterHelper.ToRealtiesViewModel(realty);

                    var typology = await _typologyRepository.GetByIdAsync(realty.TypologyId);
                    if (typology != null)
                    {
                        model.Typologies = _typologyRepository.GetComboTypologies();
                    }
                    var propertyType = await _propertyTypeRepository.GetByIdAsync(realty.PropertyTypeId);
                    if (propertyType != null)
                    {
                        model.PropertyTypes = _propertyTypeRepository.GetComboPropertyType();

                    }
                    var energyClass = await _energyClassRepository.GetByIdAsync(realty.EnergyClassId);
                    if (energyClass != null)
                    {
                        model.EnergiesClass = _energyClassRepository.GetComboEnergyClass();

                        return View(model);
                    }
                    
                }
            }


            return new NotFoundViewResult("RealtyNotFound");
        }


        //// POST: Products/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Cliente")]
        public async Task<IActionResult> Edit(RealtyViewModel modelViewModel)
        {

            if (ModelState.IsValid)
            {
                try
                {

                    Guid imageId = modelViewModel.ImageId;

                    if (modelViewModel.ImageFile != null && modelViewModel.ImageFile.Length > 0)
                    {

LimaArrendamentos/Controllers/UsersController.cs
using LimaArrendamentos.Data.Entities;
using LimaArrendamentos.Helpers;
using LimaArrendamentos.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LimaArrendamentos.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserHelper _userHelper;
        private readonly UserManager<User> _userManager;
        private readonly IConfiguration _configuration;

        public UsersController(
            IUserHelper userHelper,
            UserManager<User> userManager,
            IConfiguration configuration)
        {
            _userHelper = userHelper;
            _userManager = userManager;
            _configuration = configuration;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _userManager.GetUsersInRoleAsync("Cliente");
            var clients = new List<RegisterNewUserViewModel>();

            foreach (User user in users)
            {
                var model = new RegisterNewUserViewModel();
                //model.Id = user.Id;
                model.FirstName = user.FirstName;
                model.LastName = user.LastName;
                model.Address = user.Address;
                model.PhoneNumber = user.PhoneNumber;
                model.Username = user.UserName;
                clients.Add(model);
            }

            return View(clients);
        }

        public async Task<IActionResult> Staff()
        {
            var users = await _userManager.GetUsersInRoleAsync("Staff");
            var clients = new List<RegisterNewUserViewModel>();

            foreach (User user in users)
            {
                var model = new RegisterNewUserViewModel();
                //model.Id = user.Id;
                model.FirstName = user.FirstName;
                model.LastName = user.LastName;
                model.Address = user.Address;
                model.PhoneNumber = user.PhoneNumber;
                model.Username = user.UserName;
                clients.Add(model);
            }

            return View(clients);
        }

    }
}

LimaArrendamentos/Views/Shared/_DashboardLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <title>@ViewBag.Title | LimArrendamentos</title>

    @* basic metas *@
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    @* site metas *@
    <meta name="description" content="WebSite criado para o Projeto Final
          do curso de Técnico/a Especialista em Tecnologias e Programação de Sistemas de Informação - CET57 2021">
    <meta name="keywords" content="arrendamentos, procurar casa, alugar casa, cet57, cinel">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Ana Catarina Lima, Miguel Ribeiro, Pedro Maio" />


    @* mobile metas *@
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="~/img/logo.png" type="image/x-icon">

    @* bootstrap css *@
    <link rel="stylesheet" href="~/Dashboard/assets/plugins/bootstrap/css/bootstrap.min.css" />

    @* plugins css *@
    <link rel="stylesheet" href="~/Dashboard/assets/plugins/charts-c3/c3.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />

    @* core css *@
    <link rel="stylesheet" href="~/Dashboard/assets/css/main.css" />
    <link rel="stylesheet" href="~/Dashboard/assets/css/theme1.css" />

</head>

<body>

    <div class="page-loader-wrapper">
        <div class="loader">
        </div>
    </div>

    <div id="left-sidebar" class="sidebar">     
        <a asp-controller="Home" asp-action="Index">
            <img style="width: 60%" src="~/img/logo.png" class="ml-3 mt-3"/>
            <h5 class="brand-name text-dark">LimArrendamentos</h5>
        </a>

        <hr />

        <nav id="left-sidebar-nav" class="sidebar-nav">

            <ul class="metismenu">
                <li class="g_heading" style="font-size: 14px;">
                    <a asp-controller="Dashboard"
                       class="sidebar-link waves-effect waves-dark"
                       aria-expanded="false">Página Principal</a>
                </li>

                @* if user is admin *@
                @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin"))
                {
                    <li class="g_heading" style="font-size: 14px;">
                        <a asp-controller="Users" asp-action="Index"
                           class="sidebar-link waves-effect waves-dark"
                           aria-expanded="false">
                            Clientes
                        </a>
                    </li>

                    <li class="g_heading" style="font-size: 14px;">
                        <a asp-controller="Users" asp-action="Staff"
                           class="sidebar-link waves-effect waves-dark"
                           aria-expanded="false">
                            Funcionários
                        </a>
                    </li>

                    <li class="g_heading" style="font-size: 14px;">
                        <a asp-controller="Realty" asp-action="Index"
                           class="sidebar-link waves-effect waves-dark"
                           aria-expanded="false">
                            Imóveis
                        </a>
                    </li>

                    <li class="g_heading" style="font-size: 14px;">
                        <a asp-controller="Home" asp-action="Index"
                           class="sidebar-link waves-effect waves-dark"
                           aria-expanded="false">
                            Contratos
                        </a>
                    </li>

                }

                @* if user is client *@
                @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Cliente"))
                {
                    <li class="g_heading" style="font-size: 14px;">
                        <a asp-controller="Realty" asp-action="Create"
                           class="sidebar-link waves-effect waves-dark"
                           aria-expanded="false">
                            Novo Anúncio
                        </a>
                    </li>


                    <li class="g_heading" style="font-size: 14px;">
                        <a asp-controller="Realty" asp-action="Index"
                           class="sidebar-link waves-effect waves-dark"
                           aria-expanded="false">
                            Os Meus Imóveis
                        </a>
                    </li>

                    <li class="g_heading" style="font-size: 14px;">
                        <a asp-controller="Home" asp-action="Index"
                           class="sidebar-link waves-effect waves-dark"
                           aria-expanded="false">
                            Favoritos
                        </a>
                    </li>
                }

                <li class="g_heading mt-5" style="font-size: 14px;">
                    <a asp-controller="Account" asp-action="ChangeUser"
                       class="sidebar-link waves-effect waves-dark"
                       aria-expanded="false">Modificar Perfil</a>
                </li>
            </ul>
        </nav>
    </div>

    <div class="page">
        <div id="page_top" class="section-body" style="background-color: #22242b;">
            <div class="container-fluid">

                <div class="page-header border-bottom-0">
                    <div class="left">
                        <h5 class="text-white" style="padding: 10px 0 10px 0;">Painel de Controlo</h5>
                    </div>
                </div>

            </div>
        </div>

        
        @* dashboard content *@
        <div class="container mt-5">

            <main role="main" class="pb-3">
                @RenderBody()
            </main>

        </div>

    </div>

    @* scripts section *@
    <script src="~/Dashboard/assets/bundles/lib.vendor.bundle.js"></script>
    <script src="~/Dashboard/assets/bundles/apexcharts.bundle.js"></script>
    <script src="~/Dashboard/assets/bundles/counterup.bundle.js"></script>
    <script src="~/Dashboard/assets/bundles/knobjs.bundle.js"></script>
    <script src="~/Dashboard/assets/bundles/c3.bundle.js"></script>
    <script src="~/Dashboard/assets/js/core.js"></script>
    <script src="~/Dashboard/assets/js/page/project-index.js"></script>

    @* support button *@
    <script>
        (function () {
            var options = {
                email: "limarrendamentos@gmail.com", // Email
                call_to_action: "Precisa de ajuda?", // Call to action
                position: "right", // Position may be 'right' or 'left'
            };
            var proto = document.location.protocol, host = "getbutton.io", url = proto + "//static." + host;
            var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = url + '/widget-send-button/js/init.js';
            s.onload = function () { WhWidgetSendButton.init(host, proto, options); };
            var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);
        })();
    </script>

</body>
</html>

LimaArrendamentos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <title>@ViewBag.Title | LimArrendamentos</title>

    @* basic metas *@
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    @* site metas *@
    <meta name="description" content="WebSite criado para o Projeto Final
          do curso de Técnico/a Especialista em Tecnologias e Programação de Sistemas de Informação - CET57 2021">
    <meta name="keywords" content="arrendamentos, procurar casa, alugar casa, cet57, cinel">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Ana Catarina Lima, Miguel Ribeiro, Pedro Maio" />

    @* mobile metas *@
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="~/img/logo.png" type="image/x-icon">

    @* css styles *@
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style.css" />

    @* font styles *@
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i,900%7cRoboto:400,400i,500,500i,700,700i&display=swap">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,700|Raleway:300,400,500,700">

    @* libraries *@
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />



</head>

<body>

    @* navbar section *@
    <header class="header-section" style="margin-top: -20px; position: sticky; z-index: 1;
            background-color: #22242b; box-shadow: 0 0 10px 0;">

        <div class="container">

            <nav class="navbar navbar-expand-lg navbar-dark text-uppercase" style="background-color: #22242b;">

                <a class="nav navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="~/img/logo.png" width="35" height="35" alt="logo" />
                    <span>LimArrendamentos</span>
                </a>

                <button class="navbar-toggler fas fa-grip-lines" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                </button>

                <div class="collapse navbar-collapse main-menu" id="navbarSupportedContent">

                    <ul class="navbar-nav">

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home"
                               asp-action="Index" asp-fragment="searchSection">Procurar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home"
                               asp-action="Index" asp-fragment="aboutSection">Sobre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home"
                               asp-action="Index" asp-fragment="contactsSection">Contactos</a>
                        </li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Realty" asp-action="Index1">Anúncios</a></li>



                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link font-weight-bold" asp-controller="Dashboard" asp-action="Index"
                                   style="color: white;">Painel de Controlo</a>
                            </li>



                            <li class="nav-item">
                                <a class="nav-link font-weight-bold" asp-controller="Account" asp-action="Logout"
                                   style="color: white;">Sair</a>
                            </li>


                        }
                        else
                        {
                            <li class="nav-item" style="margin-left: 10px; margin-right: -20px;">
                                <a class="nav-link font-weight-bold" asp-controller="Account" asp-action="Login"
                                   style="color: white;">Entrar</a>
                            </li>
                            <li class="nav-item" style="margin-left: 10px;">
                                <a class="nav-link font-weight-bold" asp-controller="Account" asp-action="Register"
                                   style="color: white;">Registar</a>
                            </li>
                        }

                    </ul>

                </div>

            </nav>
        </div>
    </header>


    <div class="container mt-5 min-vh-100">
        <main role="main">
            @RenderBody()
        </main>
    </div>


    @* footer section *@
    <footer class="footer-section pt-4 mt-5 position-relative">
        <div class="copyright text-center">
            &copy; @DateTime.Now.Year TODOS OS DIREITOS RESERVADOS | ANA CATARINA LIMA - MIGUEL RIBEIRO<br />
            CET57 - PROJETO DE TECNOLOGIAS E PROGRAMAÇÃO DE SISTEMAS DE INFORMAÇÃO | Prof. ANTÓNIO PACHECO - Prof. JOÃO GALAMBA - Prof. RAFAEL SANTOS - Profª. SUSANA PIMENTEL
        </div>
    </footer>

</body>
</html>

<script src="~/js/jquery-3.2.1.min.js"></script>
<script src="~/js/jquery.magnific-popup.min.js"></script>
<script src="~/js/main.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/jquery.slicknav.min.js"></script>


@await RenderSectionAsync("scripts", required: false)